import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useSearchContext } from '../hooks'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const { state } = useSearchContext();
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Fake EC Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>{state.value}</p>

    </div>
  )
}

export default Home
